before_build:  
  - .paket\paket.exe restore

build_script:
  - ps: .\build.ps1 -Target CI -verbosity Verbose -configuration Release

artifacts:
  - path: 'nugets\*.nupkg'
  - path: coverage
    type: zip

cache:
  - packages -> paket.lock
  
deploy:
  - provider: Environment
    name: NuGet
    on:
      branch: /v\d\.\d(\.\d)?/
      appveyor_repo_tag: true