before_build:
  - .paket\paket.exe restore
  - dotnet --version
  - ps: gitversion /l console /output buildserver /updateassemblyinfo

build_script:
  - ps: .\build.ps1 -Target CI -verbosity Verbose -configuration Release

test: off

artifacts:
  - path: 'nugets\*.nupkg'
  - path: coverage
    type: zip

deploy:
  - provider: Environment
    name: NuGet
    on:
      branch: /v\d\.\d(\.\d)?/
      appveyor_repo_tag: true