install:
  - choco install gitversion.portable -pre -y
  
before_build:  
  - .paket\paket.bootstrapper.exe prerelease
  - .paket\paket.exe restore
  - ps: gitversion /l console /output buildserver

build:
  project: Nancy.Routing.UriTemplates.sln

configuration: Release

test:
  assemblies:
    - Nancy.Routing.UriTemplates.Tests.*.dll

after_build:
  - .paket\paket.exe pack output nugets include-referenced-projects version %GitVersion_NuGetVersion%
  
after_test:
  - .\packages\OpenCover\tools\OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:"tests\Nancy.Routing.UriTemplates.Tests\bin\Release\Nancy.Routing.UriTemplates.Tests.dll tests\Nancy.Routing.UriTemplates.Tests.Functional\bin\Release\Nancy.Routing.UriTemplates.Tests.Functional.dll -noshadow -appveyor" -returntargetcode -filter:"+[Nancy.Routing.UriTemplates*]* -[Nancy.Routing.UriTemplates.Tests*]* -[Test*]*" -hideskipped:All -output:.\coverage.xml
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - pip install codecov
  - codecov -f "coverage.xml"

artifacts:
  - path: 'nugets\*.nupkg'
  - path: coverage.xml

cache:
  - packages -> paket.lock
  
deploy:
  - provider: Environment
    name: NuGet
    on:
      branch: /v\d\.\d(\.\d)?/
      appveyor_repo_tag: true